[2023-11-18 12:43:10 +0000] [21149] [INFO] Starting gunicorn 21.2.0
[2023-11-18 12:43:10 +0000] [21149] [INFO] Listening at: http://0.0.0.0:8001 (21149)
[2023-11-18 12:43:10 +0000] [21149] [INFO] Using worker: sync
[2023-11-18 12:43:10 +0000] [21168] [INFO] Booting worker with pid: 21168
[2023-11-18 12:43:10 +0000] [21169] [INFO] Booting worker with pid: 21169
[2023-11-18 12:43:11 +0000] [21170] [INFO] Booting worker with pid: 21170
[2023-11-18 12:43:11 +0000] [21171] [INFO] Booting worker with pid: 21171
[2023-11-18 12:48:51 +0000] [21168] [INFO] Worker exiting (pid: 21168)
[2023-11-18 12:48:51 +0000] [21170] [INFO] Worker exiting (pid: 21170)
[2023-11-18 12:48:51 +0000] [21171] [INFO] Worker exiting (pid: 21171)
[2023-11-18 12:48:51 +0000] [21169] [INFO] Worker exiting (pid: 21169)
[2023-11-18 12:48:51 +0000] [21149] [INFO] Handling signal: term
[2023-11-18 12:48:51 +0000] [21149] [ERROR] Worker (pid:21168) was sent SIGTERM!
[2023-11-18 12:48:51 +0000] [21149] [ERROR] Worker (pid:21169) was sent SIGTERM!
[2023-11-18 12:48:51 +0000] [21149] [ERROR] Worker (pid:21170) was sent SIGTERM!
[2023-11-18 12:48:51 +0000] [21149] [ERROR] Worker (pid:21171) was sent SIGTERM!
[2023-11-18 12:48:51 +0000] [21149] [INFO] Shutting down: Master
[2023-11-18 12:49:15 +0000] [21403] [INFO] Starting gunicorn 21.2.0
[2023-11-18 12:49:15 +0000] [21403] [INFO] Listening at: http://0.0.0.0:8001 (21403)
[2023-11-18 12:49:15 +0000] [21403] [INFO] Using worker: sync
[2023-11-18 12:49:15 +0000] [21420] [INFO] Booting worker with pid: 21420
[2023-11-18 12:49:15 +0000] [21423] [INFO] Booting worker with pid: 21423
[2023-11-18 12:49:15 +0000] [21424] [INFO] Booting worker with pid: 21424
[2023-11-18 12:49:15 +0000] [21425] [INFO] Booting worker with pid: 21425
[2023-11-18 12:53:06 +0000] [21403] [INFO] Handling signal: term
[2023-11-18 12:53:06 +0000] [21424] [INFO] Worker exiting (pid: 21424)
[2023-11-18 12:53:06 +0000] [21425] [INFO] Worker exiting (pid: 21425)
[2023-11-18 12:53:06 +0000] [21420] [INFO] Worker exiting (pid: 21420)
[2023-11-18 12:53:06 +0000] [21423] [INFO] Worker exiting (pid: 21423)
[2023-11-18 12:53:06 +0000] [21403] [ERROR] Worker (pid:21420) was sent SIGTERM!
[2023-11-18 12:53:06 +0000] [21403] [ERROR] Worker (pid:21425) was sent SIGTERM!
[2023-11-18 12:53:06 +0000] [21403] [ERROR] Worker (pid:21423) was sent SIGTERM!
[2023-11-18 12:53:06 +0000] [21403] [ERROR] Worker (pid:21424) was sent SIGTERM!
[2023-11-18 12:53:06 +0000] [21403] [INFO] Shutting down: Master
[2023-11-18 13:02:16 +0000] [23587] [INFO] Starting gunicorn 21.2.0
[2023-11-18 13:02:16 +0000] [23587] [INFO] Listening at: http://0.0.0.0:8001 (23587)
[2023-11-18 13:02:16 +0000] [23587] [INFO] Using worker: sync
[2023-11-18 13:02:16 +0000] [23606] [INFO] Booting worker with pid: 23606
[2023-11-18 13:02:16 +0000] [23607] [INFO] Booting worker with pid: 23607
[2023-11-18 13:02:16 +0000] [23608] [INFO] Booting worker with pid: 23608
[2023-11-18 13:02:16 +0000] [23609] [INFO] Booting worker with pid: 23609
[2023-11-18 15:13:57 +0000] [23587] [INFO] Handling signal: hup
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/home/basil/web-dev-2023/lab1/ve/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 223, in run
    self.log.info("Handling signal: %s", signame)
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/glogging.py", line 278, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
    self.log.error(msg)
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/glogging.py", line 272, in error
    self.error_log.error(msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1093, in emit
    self.handleError(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1007, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
  File "/usr/lib/python3.8/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/usr/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/usr/lib/python3.8/traceback.py", line 366, in extract
    f.line
  File "/usr/lib/python3.8/traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/usr/lib/python3.8/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python3.8/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python3.8/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "/usr/lib/python3.8/tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "/usr/lib/python3.8/tokenize.py", line 363, in detect_encoding
    first = read_or_stop()
  File "/usr/lib/python3.8/tokenize.py", line 321, in read_or_stop
    return readline()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
    self.log.error(msg)
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/glogging.py", line 272, in error
    self.error_log.error(msg, *args, **kwargs)
Message: 'Worker (pid:23609) was sent SIGHUP!'
Arguments: ()
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/home/basil/web-dev-2023/lab1/ve/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 223, in run
    self.log.info("Handling signal: %s", signame)
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/glogging.py", line 278, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
    self.log.error(msg)
  File "/home/basil/web-dev-2023/lab1/ve/lib/python3.8/site-packages/gunicorn/glogging.py", line 272, in error
    self.error_log.error(msg, *args, **kwargs)
Message: 'Worker (pid:23607) was sent SIGHUP!'
Arguments: ()
[2023-11-18 15:13:57 +0000] [23587] [INFO] Hang up: Master
[2023-11-18 15:13:57 +0000] [27236] [INFO] Booting worker with pid: 27236
[2023-11-18 15:13:57 +0000] [27237] [INFO] Booting worker with pid: 27237
[2023-11-18 15:13:57 +0000] [27238] [INFO] Booting worker with pid: 27238
[2023-11-18 15:13:57 +0000] [27239] [INFO] Booting worker with pid: 27239
[2023-11-19 11:42:22 +0000] [27238] [INFO] Worker exiting (pid: 27238)
[2023-11-19 11:42:22 +0000] [23587] [INFO] Handling signal: term
[2023-11-19 11:42:22 +0000] [23587] [ERROR] Worker (pid:27237) was sent SIGHUP!
[2023-11-19 11:42:22 +0000] [23587] [ERROR] Worker (pid:27236) was sent SIGHUP!
[2023-11-19 11:42:22 +0000] [23587] [ERROR] Worker (pid:27239) was sent SIGHUP!
[2023-11-19 11:42:22 +0000] [23587] [ERROR] Worker (pid:27238) was sent SIGHUP!
[2023-11-19 11:42:22 +0000] [23587] [INFO] Shutting down: Master
